# Generated by Django 5.2.4 on 2026-04-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='show_on_market',
            field=models.BooleanField(default=True),
        ),
    ]
