# Generated by Django 5.2.4 on 2025-08-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_is_main_image_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='videos_url',
        ),
    ]
