# Generated by Django 5.2.4 on 2025-09-01 03:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_created_at_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField()),
                ('ended_at', models.DateTimeField(default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
            ],
        ),
    ]
