# Generated by Django 5.2.4 on 2025-09-01 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_promoted_productpromotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpromotion',
            name='promo_price',
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
    ]
