# Generated by Django 5.2.4 on 2025-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_payment_advertisement_payment_is_successful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_main_image',
            field=models.BooleanField(default=False),
        ),
    ]
