# Generated by Django 5.2.4 on 2025-09-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_is_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
