# Generated by Django 5.2.4 on 2025-09-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='product',
            new_name='products',
        ),
    ]
