# Generated by Django 5.2.4 on 2025-09-05 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_ad_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='products',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='seller',
        ),
        migrations.AddField(
            model_name='ad',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='products.product'),
        ),
    ]
