# Generated by Django 5.2.4 on 2025-09-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_quantity_stock_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='orders/pdf/'),
        ),
    ]
