# Generated by Django 5.2.4 on 2025-09-11 22:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_order_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_promoted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sponsored',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('generic', 'Annonce Générale'), ('sponsored', 'Sponsorisation Produit')], default='generic', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ad',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('popular', 'Popular')], default='new', max_length=10),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('message', models.TextField()),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductPromotion',
        ),
    ]
