# Generated by Django 5.2.4 on 2025-09-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_is_promoted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='message',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='poster',
        ),
    ]
