# Generated by Django 5.2.4 on 2025-09-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_online',
        ),
    ]
