"""Nouvelle base propre

Revision ID: 13219f2538c5
Revises: 94b86605f4e0
Create Date: 2025-04-19 13:45:42.498250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13219f2538c5'
down_revision: Union[str, None] = '94b86605f4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
