"""Nouvelle base propre

Revision ID: 94b86605f4e0
Revises: ef063315eadb
Create Date: 2025-04-19 13:07:03.614529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b86605f4e0'
down_revision: Union[str, None] = 'ef063315eadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
