"""Renommage des champs produit

Revision ID: 9e9997024571
Revises: 
Create Date: 2025-04-18 19:31:50.050582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e9997024571'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_id_message', table_name='messages')
    op.drop_table('messages')
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'paid', 'draft', name='orderstatus'),
               existing_nullable=True)
    op.add_column('products', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('status', sa.Enum('draft', 'published', 'unpublished', name='productstatus'), nullable=True))
    op.drop_column('products', 'images_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('images_list', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('products', 'status')
    op.drop_column('products', 'images')
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'paid', 'draft', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('messages',
    sa.Column('id_message', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mail_or_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_message', name='messages_pkey')
    )
    op.create_index('ix_messages_id_message', 'messages', ['id_message'], unique=False)
    # ### end Alembic commands ###
