"""Nouvelle base propre

Revision ID: b708130af6ab
Revises: bd0acfc3163f
Create Date: 2025-04-19 14:43:07.313195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b708130af6ab'
down_revision: Union[str, None] = 'bd0acfc3163f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
