"""Nouvelle base propre

Revision ID: bd0acfc3163f
Revises: 13219f2538c5
Create Date: 2025-04-19 14:38:49.192116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0acfc3163f'
down_revision: Union[str, None] = '13219f2538c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
