# Generated by Django 5.2.4 on 2025-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_card'),
        ),
    ]
