# Generated by Django 5.2.4 on 2025-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_mdp_timeout_remove_user_session_mdp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='about',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='loyal_customers',
            field=models.ManyToManyField(related_name='loyal_customers', to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slogan',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='BrandProfile',
        ),
    ]
