# Generated by Django 5.2.4 on 2025-08-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('users', '0003_sellerprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='products.category'),
        ),
    ]
