# Generated by Django 5.2.4 on 2025-08-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('users', '0004_sellerprofile_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='categories',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
