# Generated by Django 5.2.4 on 2025-08-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('users', '0005_remove_sellerprofile_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
    ]
