# Generated by Django 5.2.4 on 2025-08-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_productspreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='force_payment',
            field=models.BooleanField(default=False),
        ),
    ]
