# Generated by Django 5.2.4 on 2025-08-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sellerprofile_force_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerstatistics',
            name='total_loyal_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
