# Generated by Django 5.2.4 on 2025-09-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_sellerstatistics_total_loyal_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
