# Generated by Django 5.2.4 on 2025-09-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_sellerprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_authenticated',
        ),
    ]
