# Generated by Django 5.2.4 on 2025-09-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
