# Generated by Django 5.2.4 on 2025-09-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='show_on_market',
            field=models.BooleanField(default=False),
        ),
    ]
