# Generated by Django 5.2.4 on 2025-09-08 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_sellerprofile_show_on_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='loyal_customers',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
