# Generated by Django 5.2.4 on 2025-09-08 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_sellerprofile_loyal_customers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
