# Generated by Django 5.2.4 on 2025-09-13 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_sellerprofile_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerstatistics',
            name='user',
        ),
        migrations.AddField(
            model_name='sellerstatistics',
            name='seller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.sellerprofile'),
        ),
        migrations.AddField(
            model_name='sellerstatistics',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
