# Generated by Django 5.2.4 on 2025-09-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_sellerstatistics_user_sellerstatistics_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerstatistics',
            old_name='total_loyal_customers',
            new_name='total_subscribers',
        ),
    ]
