# Generated by Django 5.2.4 on 2025-09-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_total_loyal_customers_sellerstatistics_total_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
