# Generated by Django 5.2.4 on 2025-09-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sent_date',
            new_name='created_at',
        ),
    ]
