# Generated by Django 5.2.4 on 2025-09-17 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_sent_date_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
