# Generated by Django 5.2.4 on 2025-09-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_sellerprofile_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
    ]
