# Generated by Django 5.2.4 on 2025-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_customuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
