# Generated by Django 5.2.4 on 2025-09-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_sellerprofile_premium_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
    ]
