# Generated by Django 5.2.4 on 2025-10-10 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_delivererprofile_delete_deliverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivererprofile',
            name='deliver_to',
            field=models.ManyToManyField(blank=True, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivererprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivererprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('on_delivery', 'En livraison'), ('paused', 'En pause')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='delivererprofile',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivererprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_user_image'),
        ),
        migrations.AddField(
            model_name='delivererprofile',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_vehicle_image'),
        ),
        migrations.AddField(
            model_name='delivererprofile',
            name='vehicle_plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
