# Generated by Django 5.2.4 on 2026-04-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_in_stock_product_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
