# Generated by Django 5.2.4 on 2026-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderitem_seller_paid_orderitem_seller_paid_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='address_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
