# Generated by Django 5.2.4 on 2026-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('home', 'Livraison à domicile'), ('relay', 'Point relais')], default='home', max_length=10),
        ),
    ]
